# put your python code here
a = input('')
b = input('')
c = input('')
d = input('')
print(b, c, d, sep = a)

a = input('')
b = input('')
c = input('')
d = input('')
print(b, end = a)
print(c, end = a)
print(d)

a = input('')
b = input('')
c = input('')
d = input('')
print(b, c, d, sep = a)